server:
  port: 8084
spring:
  application:
    name: API-GATEWAY

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: USER-SERVICE
              uri: lb://USER-SERVICE
              predicates:
                - Path=/users/**
              filters:
                - TokenRelay

            - id: HOTEL-SERVICE
              uri: lb://HOTEL-SERVICE
              predicates:
                - Path=/hotels/**
              filters:
                - TokenRelay

            - id: RATING-SERVICE
              uri: lb://RATING-SERVICE
              predicates:
                - Path=/ratings/**
              filters:
                - TokenRelay

  # OAuth2 resource server — validates JWT tokens on every request
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-8mw8jsjdi3rtx7xx.us.auth0.com/   # Spring auto-fetches JWKS from here
      client:
        registration:
          auth0:
            client-id: blimXmk40g2R6LQxyAHAfNucjMN6uUQM
            client-secret: DCsiGz5d7YnNo54AEtPH6fQPzYJ-asBw0VtJ1gHeFh5_3nT576iGODi1GEp7igfI

        provider:
          auth0:
            issuer-uri: https://dev-8mw8jsjdi3rtx7xx.us.auth0.com/

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka