server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/microservice_hotel
    username: #DBusername
    password: #DbPwd
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE
  config:
    import: configserver:http://localhost:8085

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-8mw8jsjdi3rtx7xx.us.auth0.com/

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka